### ISSUE TITLE
Exclude `run_app.R` from code coverage report

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#143]
We cannot test the Shiny app yet. Up until then, exclude it from the code coverage report. See [https://covr.r-lib.org/](https://covr.r-lib.org/), section '.covrignore file' how to ignore it from Codecov.

**Comment by richelbilderbeek** [comment]
I just wrote down what @FrieseWoudloper wanted to do. I guess she'd enjoy fixing this one :+1:

**Comment by FrieseWoudloper** [comment]
To Do:
- Add `.covrignore` file to project root. It should probably contain something like:
```
R/app.R
R/run_app.R
```
- Add `.covrignore` file to `.RBuildignore`.

**Comment by janclod** [comment]
What do you think? Are we already able to test shiny app?
Let's not exclude app.R, since it is now covered :)

Codecov of the develop branch after pull request [https://github.com/informalr/informalr/pull/148](url)
![image](https://user-images.githubusercontent.com/6673668/101241544-40633e80-36f7-11eb-8816-0de0eb39ba1e.png)

**Comment by richelbilderbeek** [comment]
> Let's not exclude app.R, since it is now covered :)

I agree! Well done to the both of you!
